version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: godev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qgtodo
    ports:
      - "5432:5432"
    volumes:
      - ./assets/sqlc/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  todoserver:
    links:
      - db
    build: .
    environment:
      QGTODO_PG_HOST: db
      QGTODO_PG_USER: godev
      QGTODO_PG_PW: password
      QGTODO_PG_PORT: 5432
      QGTODO_PG_DB: qgtodo
    depends_on:
      - db
    ports:
      - "8000:8000"